todo/urls.py
from django.urls import path

from todo.views import HomePageView, TagListView, CompleteTaskView, UndoTaskView, TaskCreateView, TaskUpdateView, \
    TaskDeleteView, TagCreateView, TagUpdateView, TagDeleteView

urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path('complete_task/<int:pk>/', CompleteTaskView.as_view(), name='complete_task'),
    path('undo_task/<int:pk>/', UndoTaskView.as_view(), name='undo_task'),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo"

todo_list/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_date = models.DateTimeField(auto_now_add=True)
    dedline = models.DateTimeField(blank=True, null=True)
    implementation = models.BooleanField()
    tags = models.ManyToManyField(Tag, related_name="tasks")

todo/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic, View
from django.views.decorators.http import require_POST

from todo.models import Tag, Task


class HomePageView(generic.ListView):
    model = Task
    template_name = "todo/index.html"


class TagListView(generic.ListView):
    model = Tag


class CompleteTaskView(View):
    def post(self, request, pk):
        task = get_object_or_404(Task, id=pk)
        task.implementation = True
        task.save()
        return redirect("todo:index")


class UndoTaskView(View):
    def post(self, request, pk):
        task = get_object_or_404(Task, id=pk)
        task.implementation = False
        task.save()
        return redirect("todo:index")


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">All tags</a></li>
</ul>

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% if task_list %}
    <ul>
      {% for task in task_list %}
          <div class="container">
            <p>
              {{ task.content }}
              {% if task.implementation %}
                <span style="color: green;">Done</span>
              {% else %}
                <span style="color: red;">Not done</span>
              {% endif %}
              {% if task.implementation %}
                <form action="{% url 'todo:undo_task' task.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit">Undo</button>
                </form>
              {% else %}
                <form action="{% url 'todo:complete_task' task.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit">Complete</button>
                </form>
              {% endif %}
            </p>
            <p>
              {{ task.created_date }} {{ task.dedline }}
            </p>
            <p>
              {% for tag in task.tags.all %}
                {{ tag.name }}
              {% endfor %}
              <a href="{% url 'todo:task-update' pk=task.pk %}">
                Update
              </a>
              <a style="color: red"
                href="{% url 'todo:task-delete' pk=task.id %}">
                Delete
              </a>
            </p>
          </div>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no tasks in TODO</p>
  {% endif %}
{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tag List
    <a href="{% url 'todo:tag-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.id }}
          </td>
          <td>
              {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'todo:tag-update' pk=tag.id %}" >
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
               href="{% url 'todo:tag-delete' pk=tag.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}<a href="#">
    </table>

  {% else %}
      <p>There are no tag in the TODO.</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}